const API_URL= import.meta.env.VITE_API_URL;
const TEAM_POKEMON= import.meta.env.VITE_TEAM_POKEMON;
const POKEMON_PAGE_LIMIT= import.meta.env.VITE_POKEMON_PAGE_LIMIT;
const INITIAL_POKEMON_LIMIT= import.meta.env.VITE_INITIAL_POKEMON_LIMIT;

export const ENV = {
  API_URL,
  TEAM_POKEMON,
  POKEMON_PAGE_LIMIT,
  INITIAL_POKEMON_LIMIT,
};